### ISSUE TITLE
Exlude "unnamed" from the ranks

### ISSUE THREAD

**Issue by Croydon** [andrius4669/zeromod-sauerbraten#6]
Title should be self explaining :)

**Comment by andrius4669** [comment]
eeeeeh? what ranks? do you mean awards which are shown at the end of match?

**Comment by Croydon** [comment]
The |AoG| Insta CTF server shows ranks if somebody is connecting based on the username. "unnamed"s should be excluded there. Demophobia (yeah, I know another mod) has something similar and rank #1 is "unnamed" :/

Anyway, after you have no idea what I meant, that isn't even an offical zeromod feature? :D

**Comment by andrius4669** [comment]
well, first of all, zeromod-sauerbraten does not include any ranking feature. statistics about clients aren't being stored anywhere.
if I ever wanted to include it, I probably would rely on authkey/password to identify clients, or at least really wouldn't include "unnamed" players in stored statistics.
what you probably wanted to refer to is https://github.com/Jed-/zeromod-mod project, since iirc it does include ranking. I will notify jed and sata to fix their stuff.

**Comment by Croydon** [comment]
The people should also change their #info message, it says it's running zeromod.
